modLoader = "javafml"
loaderVersion = "[10,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "smart_pick"
version = "${version}"
displayName = "Smart Pick"
authors = "DaCommander31"
description = '''
Makes the pick block function more useful by picking a close match if the exact block isn't found.
'''
logoFile = "icon.png"

[[dependencies.smart_pick]]
modId = "neoforge"
type = "required"
versionRange = "[21.5,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.smart_pick]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.5,1.21.9)"
ordering = "NONE"
side = "BOTH"

[[mixins]]
config = "smart_pick.mixins.json"
